# Site settings
title: Inês Ochoa
tag_text: Inês Ochoa
description: ...

domain: inesochoa.github.io      
url: https://inesochoa.github.io 

# Build settings
markdown: kramdown
#markdown: redcarpet
exclude: ["README.md"]
sass:
  style: compressed